"""Reusable data-contract helpers for the Spotify analysis."""

from .data_contract import (
    CLEAN_COLUMNS,
    CLEAN_SCHEMA,
    IMPUTATION_POLICY,
    RAW_COLUMNS,
    RAW_SCHEMA,
    build_duckdb_layer,
    clean_source_rows,
    load_tracks_raw,
    missing_identifier_counts,
    parse_track_artists,
    validate_repeated_track_fields,
    validate_clean_schema,
    validate_source_schema,
)
from .data_layer import (
    CONTRACT_VERSION,
    DataContractReport,
    DataLayer,
    build_data_layer,
    canonical_file_sha256,
    contract_capsule,
)
from .feature_views import (
    CATEGORICAL_FEATURES,
    CONTINUOUS_AUDIO_FEATURES,
    HUMAN_AUDIO_FEATURES,
    HUMAN_PANEL,
    STRUCTURE_POOL,
    FeatureViewSpec,
    add_semantic_features,
    deterministic_sample,
    feature_columns,
    fit_genre_ppmi,
    genre_overlap_pairs,
    compare_genre_similarities,
    genre_audio_profiles,
    genre_membership_matrix,
    robust_pca_profiles,
)
from .statistics import (
    artist_partition,
    bh_fdr,
    coefficient_confidence_intervals,
    eligible_group_summary,
    fit_clustered_ols,
    holm_adjust,
    joint_wald_test,
    random_effects_pool,
    synthetic_imputation_metrics,
)
from .clustering import clustering_stability
from .notebook_ui import EvidenceStatus, NarrativeSection, render_narrative_section

__all__ = [
    "IMPUTATION_POLICY",
    "RAW_COLUMNS",
    "RAW_SCHEMA",
    "build_duckdb_layer",
    "clean_source_rows",
    "CLEAN_COLUMNS",
    "CLEAN_SCHEMA",
    "load_tracks_raw",
    "missing_identifier_counts",
    "parse_track_artists",
    "validate_repeated_track_fields",
    "validate_clean_schema",
    "validate_source_schema",
    "CONTRACT_VERSION",
    "DataContractReport",
    "DataLayer",
    "build_data_layer",
    "canonical_file_sha256",
    "contract_capsule",
    "CATEGORICAL_FEATURES",
    "CONTINUOUS_AUDIO_FEATURES",
    "HUMAN_AUDIO_FEATURES",
    "HUMAN_PANEL",
    "STRUCTURE_POOL",
    "FeatureViewSpec",
    "add_semantic_features",
    "deterministic_sample",
    "feature_columns",
    "fit_genre_ppmi",
    "genre_overlap_pairs",
    "compare_genre_similarities",
    "genre_audio_profiles",
    "genre_membership_matrix",
    "robust_pca_profiles",
    "bh_fdr",
    "holm_adjust",
    "random_effects_pool",
    "coefficient_confidence_intervals",
    "eligible_group_summary",
    "synthetic_imputation_metrics",
    "artist_partition",
    "fit_clustered_ols",
    "joint_wald_test",
    "clustering_stability",
    "EvidenceStatus",
    "NarrativeSection",
    "render_narrative_section",
]
